name: Deploy to AWS EBS

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from github
        uses: actions/checkout@v4
      - name: setup java 21
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'
      - name: build jar
        run: mvn clean install -DskipTests
      - name: deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: HotelBooking  # MyJavaApp springtest EbsDemo redHotel
          environment_name: HotelBooking-env      # MyJavaApp Springtest-env EbsDemo-env
          version_label: vol-0121 #12345  myVersionLabel123
          region: ap-south-1 #us-west-2 # af-south-1
          deployment_package: target/cicd.github.elasticbeanstalk-0.0.1-SNAPSHOT.jar
